pipeline {
     docker {
                                        image 'cimg/base:stable'
                                        args '-u root'
                                    }
                }
    stages {
        stage('Deploy FE') {
            agent {

             steps {
                            sh '''
                                curl https://cli-assets.heroku.com/install.sh | sh;
                                npm install -g heroku;
                                heroku git:remote -a w2w-front
                                git subtree push --prefix client/ heroku main
                            '''
                }
        }
    }
}
