pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3001 -u root'
        }
    }
    stages {
        stage('Deploy FE') {
            agent {
                docker {
                                    image 'cimg/base:stable'
                                    args '-u root'
                                }
            }
             steps {
                            sh '''
                                curl https://cli-assets.heroku.com/install.sh | sh;
                                npm install -g heroku;
                                heroku git:remote -a w2w-front
                                git subtree push --prefix client/ heroku main
                            '''
                }
        }
    }
}
